In [1]:
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib

print(np.__version__)

1.13.1


In [2]:
data = {'Weight' : ['150g', '160g', '170g', '140g', '130g', '120g'],
        'Texture': ['Bumpy', 'Bumpy', 'Bumpy', 'Smooth', 'Smooth', 'Smooth' ],
        'Label' : ['Orange', 'Orange', 'Orange', 'Apple', 'Apple', 'Apple']}

In [3]:
df = pd.DataFrame.from_dict(data)

In [4]:
df

Label Texture Weight
0  Orange   Bumpy   150g
1  Orange   Bumpy   160g
2  Orange   Bumpy   170g
3   Apple  Smooth   140g
4   Apple  Smooth   130g
5   Apple  Smooth   120g

In [5]:
df['Label'] = df['Label'].map({'Orange':0, 'Apple': 1})
df

Label Texture Weight
0      0   Bumpy   150g
1      0   Bumpy   160g
2      0   Bumpy   170g
3      1  Smooth   140g
4      1  Smooth   130g
5      1  Smooth   120g

In [6]:
df['Texture'] = df['Texture'].map({'Smooth':1, 'Bumpy': 0})
df

Label  Texture Weight
0      0        0   150g
1      0        0   160g
2      0        0   170g
3      1        1   140g
4      1        1   130g
5      1        1   120g

In [8]:
df['Weight'] = df['Weight'].map(lambda input: input.replace('g',''))
df

Label  Texture Weight
0      0        0    150
1      0        0    160
2      0        0    170
3      1        1    140
4      1        1    130
5      1        1    120

In [9]:
# Prepare Data
features = df[['Weight', 'Texture']].values
labels = df['Label'].values

features

array([['150', 0],
       ['160', 0],
       ['170', 0],
       ['140', 1],
       ['130', 1],
       ['120', 1]], dtype=object)

In [10]:
labels

array([0, 0, 0, 1, 1, 1])

In [11]:
from sklearn import tree

In [13]:
classifier = tree.DecisionTreeClassifier()
classifier.fit(features, labels)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [14]:
classifier.predict([[145,1]])

array([1])

In [15]:
from sklearn.externals import joblib
joblib.dump(classifier, 'model_orange_apple.pkl')

['model_orange_apple.pkl']

In [17]:
#load
clf = joblib.load('model_orange_apple.pkl')
clf.predict([[140,1]])

array([1])